/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package euchre;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Joe
 */
public class setupFrame extends javax.swing.JFrame {
   private Game game;
    /** Creates new form setupFrame */
   
   public setupFrame() {
        initComponents();
    }
    public setupFrame(euchreGUI g, Game gm) {
        initComponents();
        game = gm;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        backgroundPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        partnerLabel = new javax.swing.JLabel();
        opp1Label = new javax.swing.JLabel();
        opp2Label = new javax.swing.JLabel();
        partnerDifficulty = new javax.swing.JComboBox<>();
        opp1Difficulty = new javax.swing.JComboBox<>();
        opp2Difficulty = new javax.swing.JComboBox<>();
        startButton = new javax.swing.JButton();
        rulesButton = new javax.swing.JButton();

        jComboBox2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Easy", "Normal" }));
        jComboBox2.setMinimumSize(new java.awt.Dimension(71, 32));
        jComboBox2.setPreferredSize(new java.awt.Dimension(71, 32));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Euchre Setup");

        backgroundPanel.setBackground(new java.awt.Color(0, 100, 0));
        backgroundPanel.setName(""); // NOI18N

        titleLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(222, 222, 222));
        titleLabel.setText("Euchre");

        partnerLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        partnerLabel.setForeground(new java.awt.Color(222, 222, 222));
        partnerLabel.setText("Partner Difficulty");

        opp1Label.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        opp1Label.setForeground(new java.awt.Color(222, 222, 222));
        opp1Label.setText("Opponent 1 Difficulty");

        opp2Label.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        opp2Label.setForeground(new java.awt.Color(222, 222, 222));
        opp2Label.setText("Opponent 2 Difficulty");

        partnerDifficulty.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        partnerDifficulty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Easy", "Normal" }));
        partnerDifficulty.setMinimumSize(new java.awt.Dimension(71, 32));
        partnerDifficulty.setPreferredSize(new java.awt.Dimension(71, 32));
        partnerDifficulty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partnerDifficultyActionPerformed(evt);
            }
        });

        opp1Difficulty.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        opp1Difficulty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Easy", "Normal" }));
        opp1Difficulty.setMinimumSize(new java.awt.Dimension(71, 32));
        opp1Difficulty.setPreferredSize(new java.awt.Dimension(71, 32));

        opp2Difficulty.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        opp2Difficulty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Easy", "Normal" }));
        opp2Difficulty.setMinimumSize(new java.awt.Dimension(71, 32));
        opp2Difficulty.setPreferredSize(new java.awt.Dimension(71, 32));

        startButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        startButton.setText("Start Game");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        rulesButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        rulesButton.setText("Rules");

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(opp1Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(opp1Difficulty, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(opp2Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(opp2Difficulty, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(partnerLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(partnerDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                        .addComponent(rulesButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(startButton)))
                .addContainerGap())
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(titleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addGap(31, 31, 31)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partnerLabel)
                    .addComponent(partnerDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opp1Label)
                    .addComponent(opp1Difficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opp2Label)
                    .addComponent(opp2Difficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startButton)
                    .addComponent(rulesButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void partnerDifficultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partnerDifficultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_partnerDifficultyActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        int partnerDif = 1;
        int opp1Dif = 1;
        int opp2Dif = 1;
        
        if(partnerDifficulty.getSelectedItem().equals("Normal"))
            partnerDif = 2;
        if(opp1Difficulty.getSelectedItem().equals("Normal"))
            opp1Dif = 2;
        if(opp2Difficulty.getSelectedItem().equals("Normal"))
            opp2Dif = 2;
        this.dispose();
        game.startGame(partnerDif, opp1Dif, opp2Dif);
    }//GEN-LAST:event_startButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(setupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(setupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(setupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(setupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new setupFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> opp1Difficulty;
    private javax.swing.JLabel opp1Label;
    private javax.swing.JComboBox<String> opp2Difficulty;
    private javax.swing.JLabel opp2Label;
    private javax.swing.JComboBox<String> partnerDifficulty;
    private javax.swing.JLabel partnerLabel;
    private javax.swing.JButton rulesButton;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

}
